laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('marcenaria-personalizada/{marcenaria_categoria?}', ['as' => 'marcenaria-personalizada', 'uses' => 'MarcenariaController@index']);

Route::get('linha-girante/{linha_categoria?}', ['as' => 'linha-girante', 'uses' => 'LinhaController@index']);
Route::get('linha-girante/{linha_categoria}/{linha_produto}/{linha_imagem?}', ['as' => 'linha-girante.produto', 'uses' => 'LinhaController@show']);

Route::get('quem-somos', ['as' => 'quem-somos', 'uses' => 'QuemSomosController@index']);

Route::get('novidades/data/{ano}/{mes?}', ['as' => 'novidades.data', 'uses' => 'BlogController@data']);
Route::get('novidades/{blog_categoria?}', ['as' => 'novidades', 'uses' => 'BlogController@index']);
Route::get('novidades/{blog_categoria}/{blog_post}', ['as' => 'novidades.post', 'uses' => 'BlogController@show']);
Route::post('novidades/{blog_categoria}/{blog_post}', ['as' => 'novidades.comentario', 'uses' => 'BlogController@comentario']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);

    Route::resource('banners', 'BannersController');

    Route::group(['prefix' => 'marcenaria-personalizada'], function() {
        Route::resource('projetos', 'ProjetosController');
        Route::resource('projetos.imagens', 'ProjetosImagensController');
        Route::resource('imagens/categorias', 'MarcenariaController');
        Route::resource('imagens', 'MarcenariaImagensController');
    });

    Route::group(['prefix' => 'linha-girante'], function() {
        Route::resource('linhas', 'LinhasController');
        Route::resource('linhas.imagens', 'LinhasImagensController');
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::resource('produtos.imagens', 'ProdutosImagensController');
    });

    Route::resource('quem-somos/parceiros', 'ParceirosController');
    Route::resource('quem-somos', 'QuemSomosController');

    Route::resource('novidades/categorias', 'BlogCategoriasController');
    Route::resource('novidades/comentarios', 'BlogComentariosController');
    Route::resource('novidades', 'BlogPostsController');
    Route::get('novidades/comentarios/{comentarios}/aprovacao/{value}', 'BlogComentariosController@aprovacao');
    Route::post('ckeditor-upload', 'BlogPostsController@imageUpload');

    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');

    Route::resource('usuarios', 'UsuariosController');
    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Models/BlogComentario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BlogComentario extends Model
{
    protected $table = 'blog_comentarios';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function scopeOrdenados($query)
    {
        return $query->orderBy('id', 'DESC');
    }

    public function post()
    {
        return $this->belongsTo('App\Models\BlogPost', 'blog_post_id');
    }
}

laravel/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Http\Requests;
use App\Models\BlogPost;
use Illuminate\Http\Request;
use App\Models\BlogCategoria;
use App\Http\Controllers\Controller;
use App\Http\Requests\BlogComentariosRequest;

class BlogController extends Controller
{

    public function index(BlogCategoria $categoria, Request $request)
    {
        $posts = BlogPost::with('categoria')->ordenados();
        if (!empty($categoria->id)) $posts = $posts->categoria($categoria->id);

        $mes_selecionado = null;
        $ano_selecionado = null;

        if ($request->ajax()) return $posts->paginate(10);

        return view('frontend.blog.index', compact('categoria', 'mes_selecionado', 'ano_selecionado'));
    }

    public function show(BlogCategoria $categoria, BlogPost $post)
    {
        $mes_selecionado = null;
        $ano_selecionado = null;

        $data_post = Carbon::createFromFormat('d/m/Y', $post->data)->format('Y-m-d');

        $anterior = BlogPost::where('data', '<', $data_post)
                          ->orWhere(function($query) use ($data_post, $post) {
                              $query->where('data', $data_post)
                                    ->where('id', '<', $post->id);
                          })
                          ->orderBy('data', 'DESC')->orderBy('id', 'DESC')->first();

        $proximo  = BlogPost::where('data', '>', $data_post)
                          ->orWhere(function($query) use ($data_post, $post) {
                              $query->where('data', $data_post)
                                    ->where('id', '>', $post->id);
                          })->orderBy('data', 'ASC')->orderBy('id', 'ASC')->first();

        return view('frontend.blog.show', compact('post', 'anterior', 'proximo', 'mes_selecionado', 'ano_selecionado', 'categoria'));
    }

    public function data(Request $request, $ano_selecionado = null, $mes_selecionado = null)
    {
        $posts = BlogPost::with('comentariosAprovados', 'categoria')->ordenados();

        if (!$mes_selecionado) {
            $posts = $posts->whereRaw("YEAR(data) = $ano_selecionado");
        } else {
            $posts = $posts->whereRaw("YEAR(data) = $ano_selecionado AND MONTH(data) = $mes_selecionado");
        }

        if ($request->ajax()) return $posts->paginate(10);

        return view('frontend.blog.index', compact('ano_selecionado', 'mes_selecionado'));
    }

    public function comentario(BlogComentariosRequest $request, BlogCategoria $categoria, BlogPost $post)
    {
        $post->comentarios()->create($request->all());

        return response()->json(['message' => 'Comentário enviado com sucesso! Aguardando aprovação.']);
    }

}

laravel/resources/views/frontend/blog/index.blade.php
@extends('frontend.common.template')

@section('content')

    <div class="main novidades">
        <div class="center">
            <div class="title">
                <h2>Novidades em Marcenaria e Mobiliário</h2>
                <h3>acompanhe a Girante na mídia · ideias para interiores · tendências, novidades e mais!</h3>
            </div>

            @include('frontend.blog.sidebar')

            <div class="novidades-main novidades-posts">
                <div id="novidades-posts-list" data-url="{{ Request::url() }}" data-capa="{{ asset('assets/img/blog/') }}" data-link="{{ route('novidades') }}">
                    <div class="grid-sizer"></div>
                    <div class="gutter-sizer"></div>
                </div>
                <a href="#" id="novidades-load-more" class="loading">Carregar mais</a>
                <script>var current_page = 0;</script>
            </div>
        </div>
    </div>

@endsection

laravel/resources/views/frontend/blog/show.blade.php
@extends('frontend.common.template')

@section('content')

    <div class="main novidades">
        <div class="center">
            <div class="title">
                <h2>Novidades em Marcenaria e Mobiliário</h2>
                <h3>acompanhe a Girante na mídia · ideias para inteiores · tendências, novidades e mais!</h3>
            </div>

            @include('frontend.blog.sidebar')

            <div class="novidades-main novidades-post">
                <h3>{{ $post->titulo }}</h3>
                <div class="info">
                    <span class="left">
                        {{ Tools::formataDataBlog($post->data) }} · <a href="{{ route('novidades', $post->categoria->slug) }}">{{ $post->categoria->titulo }}</a>
                    </span>
                    <span class="right">
                        {{ count($post->comentariosAprovados) }} Comentário{{ (count($post->comentariosAprovados) != 1 ? 's' : '') }} · <a href="#" id="comente">Comente!</a>
                    </span>
                </div>

                <div class="texto">
                    {!! $post->texto !!}
                </div>

                <div id="comentarios">
                    <h5>COMENTÁRIOS [{{ count($post->comentariosAprovados) }}]</h5>

                    <form action="" id="form-comentario" data-url="{{ Request::url() }}">
                        <input type="text" name="autor" id="autor" placeholder="NOME" required>
                        <input type="email" name="email" id="email" placeholder="E-MAIL" required>
                        <textarea name="comentario" id="comentario" placeholder="COMENTÁRIO" required></textarea>
                        <input type="hidden" name="blog_id" id="blog_id" value="{{ $post->id }}">
                        <input type="submit" value="ENVIAR">
                        <p>Os comentários são moderados pela nossa equipe que pode optar por não exibí-los se assim achar conveniente, não cabendo ao autor do comentário qualquer alegação.</p>
                        <div id="form-resposta"></div>
                    </form>

                    <ul class="comentarios-lista">
                        @foreach($post->comentariosAprovados as $comentario)
                            <li>
                                <span class="autor">
                                    {{ Tools::formataDataBlog($comentario->created_at) }} · {{{ $comentario->autor }}}
                                </span>
                                <span class="comentario">
                                    {{{ $comentario->comentario }}}
                                </span>
                            </li>
                        @endforeach
                    </ul>
                </div>

                <div class="paginacao">
                    @if($anterior)
                    <a href="{{ route('novidades.post', [$anterior->categoria->slug, $anterior->slug]) }}" class="prev">Post Anterior</a>
                    @endif
                    <a href="#" id="topo">Topo</a>
                    @if($proximo)
                    <a href="{{ route('novidades.post', [$proximo->categoria->slug, $proximo->slug]) }}" class="next">Próximo Post</a>
                    @endif
                </div>
            </div>
        </div>
    </div>

@endsection

laravel/resources/views/frontend/blog/sidebar.blade.php
            <div class="novidades-sidebar">
                <div class="novidades-categorias">
                    @foreach($categorias_list as $cat)
                    <a href="{{ route('novidades', $cat->slug) }}" @if(isset($categoria) && $cat->id == $categoria->id && Route::currentRouteName() == 'novidades') class="active" @endif>» {{ $cat->titulo }}</a>
                    @endforeach
                </div>

                <div class="novidades-datas">
                    <?php $ano = null ?>
                    @foreach($datas as $data)
                        @if($ano != $data->ano)
                            <a href="{{ route('novidades.data', $data->ano) }}" class="ano @if($data->ano == $ano_selecionado) active @endif">
                                {{ $data->ano }}
                            </a>
                            <?php $ano = $data->ano ?>
                        @endif
                        <a href="{{ route('novidades.data', [$data->ano, $data->mes]) }}" class="mes @if($data->ano == $ano_selecionado && $data->mes == $mes_selecionado) active @endif">
                            [{{ Tools::mesExtenso($data->mes) }}]
                        </a>
                    @endforeach
                </div>
            </div>