laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('marcenaria-personalizada/{marcenaria_categoria?}', ['as' => 'marcenaria-personalizada', 'uses' => 'MarcenariaController@index']);

Route::get('linha-girante/{linha_categoria?}', ['as' => 'linha-girante', 'uses' => 'LinhaController@index']);
Route::get('linha-girante/{linha_categoria}/{linha_produto}/{linha_imagem?}', ['as' => 'linha-girante.produto', 'uses' => 'LinhaController@show']);

Route::get('quem-somos', ['as' => 'quem-somos', 'uses' => 'QuemSomosController@index']);

Route::get('novidades/data/{ano}/{mes?}', ['as' => 'novidades.data', 'uses' => 'BlogController@data']);
Route::get('novidades/{blog_categoria?}', ['as' => 'novidades', 'uses' => 'BlogController@index']);
Route::get('novidades/{blog_categoria}/{blog_post}', ['as' => 'novidades.post', 'uses' => 'BlogController@show']);
Route::post('novidades/{blog_categoria}/{blog_post}', ['as' => 'novidades.comentario', 'uses' => 'BlogController@comentario']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);

    Route::resource('banners', 'BannersController');

    Route::group(['prefix' => 'marcenaria-personalizada'], function() {
        Route::resource('projetos', 'ProjetosController');
        Route::resource('projetos.imagens', 'ProjetosImagensController');
        Route::resource('imagens/categorias', 'MarcenariaController');
        Route::resource('imagens', 'MarcenariaImagensController');
    });

    Route::group(['prefix' => 'linha-girante'], function() {
        Route::resource('linhas', 'LinhasController');
        Route::resource('linhas.imagens', 'LinhasImagensController');
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::resource('produtos.imagens', 'ProdutosImagensController');
    });

    Route::resource('quem-somos/parceiros', 'ParceirosController');
    Route::resource('quem-somos', 'QuemSomosController');

    Route::resource('novidades/categorias', 'BlogCategoriasController');
    Route::resource('novidades/comentarios', 'BlogComentariosController');
    Route::resource('novidades', 'BlogPostsController');
    Route::get('novidades/comentarios/{comentarios}/aprovacao/{value}', 'BlogComentariosController@aprovacao');
    Route::post('ckeditor-upload', 'BlogPostsController@imageUpload');

    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');

    Route::resource('usuarios', 'UsuariosController');
    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Http\Requests;
use App\Models\BlogPost;
use Illuminate\Http\Request;
use App\Models\BlogCategoria;
use App\Http\Controllers\Controller;
use App\Http\Requests\BlogComentariosRequest;

class BlogController extends Controller
{

    public function index(BlogCategoria $categoria, Request $request)
    {
        $posts = BlogPost::with('categoria')->ordenados();
        if (!empty($categoria->id)) $posts = $posts->categoria($categoria->id);

        $mes_selecionado = null;
        $ano_selecionado = null;

        if ($request->ajax()) return $posts->paginate(10);

        return view('frontend.blog.index', compact('categoria', 'mes_selecionado', 'ano_selecionado'));
    }

    public function show(BlogCategoria $categoria, BlogPost $post)
    {
        $mes_selecionado = null;
        $ano_selecionado = null;

        $data_post = Carbon::createFromFormat('d/m/Y', $post->data)->format('Y-m-d');

        $anterior = BlogPost::where('data', '<', $data_post)
                          ->orWhere(function($query) use ($data_post, $post) {
                              $query->where('data', $data_post)
                                    ->where('id', '<', $post->id);
                          })
                          ->orderBy('data', 'DESC')->orderBy('id', 'DESC')->first();

        $proximo  = BlogPost::where('data', '>', $data_post)
                          ->orWhere(function($query) use ($data_post, $post) {
                              $query->where('data', $data_post)
                                    ->where('id', '>', $post->id);
                          })->orderBy('data', 'ASC')->orderBy('id', 'ASC')->first();

        return view('frontend.blog.show', compact('post', 'anterior', 'proximo', 'mes_selecionado', 'ano_selecionado', 'categoria'));
    }

    public function data(Request $request, $ano_selecionado = null, $mes_selecionado = null)
    {
        $posts = BlogPost::with('comentariosAprovados', 'categoria')->ordenados();

        if (!$mes_selecionado) {
            $posts = $posts->whereRaw("YEAR(data) = $ano_selecionado");
        } else {
            $posts = $posts->whereRaw("YEAR(data) = $ano_selecionado AND MONTH(data) = $mes_selecionado");
        }

        if ($request->ajax()) return $posts->paginate(10);

        return view('frontend.blog.index', compact('ano_selecionado', 'mes_selecionado'));
    }

    public function comentario(BlogComentariosRequest $request, BlogCategoria $categoria, BlogPost $post)
    {
        $post->comentarios()->create($request->all());

        return response()->json(['message' => 'Comentário enviado com sucesso! Aguardando aprovação.']);
    }

}

laravel/resources/views/painel/blog/categorias/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Novidades /</small> Adicionar Categoria</h2>
    </legend>

    {!! Form::open(['route' => 'painel.novidades.categorias.store']) !!}

        @include('painel.blog.categorias.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/blog/categorias/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Novidades /</small> Editar Categoria</h2>
    </legend>

    {!! Form::model($categoria, [
        'route' => ['painel.novidades.categorias.update', $categoria->id],
        'method' => 'patch'])
    !!}

        @include('painel.blog.categorias.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/blog/categorias/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.novidades.categorias.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/blog/categorias/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.novidades.index') }}" class="btn btn-sm btn-default">
        &larr; Voltar para Novidades
    </a>

    <legend>
        <h2>
            <small>Novidades /</small> Categorias
            <a href="{{ route('painel.novidades.categorias.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Categoria</a>
        </h2>
    </legend>

    @if(!count($categorias))
    <div class="alert alert-warning" role="alert">Nenhuma categoria cadastrada.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="blog_categorias">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($categorias as $categoria)
            <tr class="tr-row" id="{{ $categoria->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $categoria->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.novidades.categorias.destroy', $categoria->id), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.novidades.categorias.edit', $categoria->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection