laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('marcenaria-personalizada/{marcenaria_categoria?}', ['as' => 'marcenaria-personalizada', 'uses' => 'MarcenariaController@index']);

Route::get('linha-girante/{linha_categoria?}', ['as' => 'linha-girante', 'uses' => 'LinhaController@index']);
Route::get('linha-girante/{linha_categoria}/{linha_produto}/{linha_imagem?}', ['as' => 'linha-girante.produto', 'uses' => 'LinhaController@show']);

Route::get('quem-somos', ['as' => 'quem-somos', 'uses' => 'QuemSomosController@index']);

Route::get('novidades/data/{ano}/{mes?}', ['as' => 'novidades.data', 'uses' => 'BlogController@data']);
Route::get('novidades/{blog_categoria?}', ['as' => 'novidades', 'uses' => 'BlogController@index']);
Route::get('novidades/{blog_categoria}/{blog_post}', ['as' => 'novidades.post', 'uses' => 'BlogController@show']);
Route::post('novidades/{blog_categoria}/{blog_post}', ['as' => 'novidades.comentario', 'uses' => 'BlogController@comentario']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);

    Route::resource('banners', 'BannersController');

    Route::group(['prefix' => 'marcenaria-personalizada'], function() {
        Route::resource('projetos', 'ProjetosController');
        Route::resource('projetos.imagens', 'ProjetosImagensController');
        Route::resource('imagens/categorias', 'MarcenariaController');
        Route::resource('imagens', 'MarcenariaImagensController');
    });

    Route::group(['prefix' => 'linha-girante'], function() {
        Route::resource('linhas', 'LinhasController');
        Route::resource('linhas.imagens', 'LinhasImagensController');
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::resource('produtos.imagens', 'ProdutosImagensController');
    });

    Route::resource('quem-somos/parceiros', 'ParceirosController');
    Route::resource('quem-somos', 'QuemSomosController');

    Route::resource('novidades/categorias', 'BlogCategoriasController');
    Route::resource('novidades/comentarios', 'BlogComentariosController');
    Route::resource('novidades', 'BlogPostsController');
    Route::get('novidades/comentarios/{comentarios}/aprovacao/{value}', 'BlogComentariosController@aprovacao');
    Route::post('ckeditor-upload', 'BlogPostsController@imageUpload');

    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');

    Route::resource('usuarios', 'UsuariosController');
    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannerRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Helpers\CropImage;

class BannersController extends Controller
{
    private $image_config = [
        'width'  => 1980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannerRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar banner: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannerRequest $request, Banner $banner)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $banner->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar banner: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $banner)
    {
        try {

            $banner->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Banner excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir banner: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BlogCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BlogCategoriasRequest;
use App\Models\BlogCategoria;
use Illuminate\Http\Request;

class BlogCategoriasController extends Controller
{
    public function index()
    {
        $categorias = BlogCategoria::ordenados()->get();

        return view('painel.blog.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.blog.categorias.create');
    }

    public function store(BlogCategoriasRequest $request)
    {
        try {

            $input = $request->all();

            BlogCategoria::create($input);
            return redirect()->route('painel.novidades.categorias.index')->with('success', 'Categoria adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar categoria: '.$e->getMessage()]);

        }
    }

    public function edit(BlogCategoria $categoria)
    {
        return view('painel.blog.categorias.edit', compact('categoria'));
    }

    public function update(BlogCategoriasRequest $request, BlogCategoria $categoria)
    {
        try {

            $input = $request->all();

            $categoria->update($input);
            return redirect()->route('painel.novidades.categorias.index')->with('success', 'Categoria alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar categoria: '.$e->getMessage()]);

        }
    }

    public function destroy(BlogCategoria $categoria)
    {
        try {

            $categoria->delete();
            return redirect()->route('painel.novidades.categorias.index')->with('success', 'Categoria excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir categoria: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BlogComentariosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\BlogComentario;
use Illuminate\Http\Request;

class BlogComentariosController extends Controller
{
    public function index()
    {
        $comentarios = BlogComentario::with('post')->ordenados()->paginate(20);

        return view('painel.blog.comentarios', compact('comentarios'));
    }

    public function destroy(BlogComentario $comentario)
    {
        try {

            $comentario->delete();
            return redirect()->route('painel.novidades.comentarios.index')->with('success', 'Comentário excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir comentário: '.$e->getMessage()]);

        }
    }

    public function aprovacao(BlogComentario $comentario, $value)
    {
        $comentario->aprovado = $value;
        $comentario->save();
    }
}

laravel/app/Http/Controllers/Painel/BlogPostsController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Helpers\CropImage;
use App\Http\Controllers\Controller;
use App\Http\Requests\BlogPostsRequest;
use App\Models\BlogCategoria;
use App\Models\BlogPost;
use Illuminate\Http\Request;

class BlogPostsController extends Controller
{
    private $image_config = [
        'width'  => 380,
        'height' => null,
        'path'   => 'assets/img/blog/'
    ];

    private $categorias;

    public function __construct()
    {
        $this->categorias = BlogCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (BlogCategoria::find($filtro)) {
            $posts = BlogPost::ordenados()->categoria($filtro)->paginate(20);
        } else {
            $posts = BlogPost::ordenados()->paginate(20);
        }

        return view('painel.blog.index', compact('categorias', 'posts', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.blog.create', compact('categorias'));
    }

    public function store(BlogPostsRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            BlogPost::create($input);
            return redirect()->route('painel.novidades.index')->with('success', 'Post adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar post: '.$e->getMessage()]);

        }
    }

    public function edit(BlogPost $post)
    {
        $categorias = $this->categorias;

        return view('painel.blog.edit', compact('categorias', 'post'));
    }

    public function update(BlogPostsRequest $request, BlogPost $post)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $post->update($input);
            return redirect()->route('painel.novidades.index')->with('success', 'Post alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar post: '.$e->getMessage()]);

        }
    }

    public function destroy(BlogPost $post)
    {
        try {

            $post->delete();
            return redirect()->route('painel.novidades.index')->with('success', 'Post excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir post: '.$e->getMessage()]);

        }
    }

    public function imageUpload(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', [
                'width'  => 800,
                'height' => null,
                'path'   => 'assets/img/blog/imagens/'
            ]);
            $response = [
                'filepath' => asset('assets/img/blog/imagens/' . $imagem)
            ];
        }

        return response()->json($response);
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\ContatoRequest;

use App\Http\Controllers\Controller;
use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class HomeController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/LinhasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\LinhasRequest;
use App\Http\Controllers\Controller;

use App\Models\Linha;
use App\Helpers\CropImage;

class LinhasController extends Controller
{
    public function index()
    {
        $linhas = Linha::ordenados()->get();

        return view('painel.linhas.index', compact('linhas'));
    }

    public function create()
    {
        return view('painel.linhas.create');
    }

    public function store(LinhasRequest $request)
    {
        try {

            $input = $request->all();

            Linha::create($input);
            return redirect()->route('painel.linha-girante.linhas.index')->with('success', 'Linha adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar linha: '.$e->getMessage()]);

        }
    }

    public function edit(Linha $linha)
    {
        return view('painel.linhas.edit', compact('linha'));
    }

    public function update(LinhasRequest $request, Linha $linha)
    {
        try {

            $input = $request->all();

            $linha->update($input);
            return redirect()->route('painel.linha-girante.linhas.index')->with('success', 'Linha alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar linha: '.$e->getMessage()]);

        }
    }

    public function destroy(Linha $linha)
    {
        try {

            $linha->delete();
            return redirect()->route('painel.linha-girante.linhas.index')->with('success', 'Linha excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir linha: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/QuemSomosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\QuemSomosRequest;
use App\Http\Controllers\Controller;

use App\Models\QuemSomos;
use App\Helpers\CropImage;

class QuemSomosController extends Controller
{
    private $image_config = [
        'width'  => 400,
        'height' => null,
        'path'   => 'assets/img/quem-somos/'
    ];

    public function index()
    {
        $quemsomos = QuemSomos::first();

        return view('painel.quem-somos.index', compact('quemsomos'));
    }

    public function update(QuemSomosRequest $request, QuemSomos $quemsomos)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $quemsomos->update($input);
            return redirect()->route('painel.quem-somos.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/produtos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Linha Girante /</small> Adicionar Produto</h2>
    </legend>

    {!! Form::open(['route' => 'painel.linha-girante.produtos.store']) !!}

        @include('painel.produtos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/produtos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Linha Girante /</small> Editar Produto</h2>
    </legend>

    {!! Form::model($produto, [
        'route' => ['painel.linha-girante.produtos.update', $produto->id],
        'method' => 'patch'])
    !!}

        @include('painel.produtos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/produtos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('produtos_categoria_id', 'Categoria') !!}
    {!! Form::select('produtos_categoria_id', $categorias, null, ['class' => 'form-control', 'placeholder' => 'Selecione']) !!}
</div>

<div class="form-group">
    {!! Form::label('linha_id', 'Linha') !!}
    {!! Form::select('linha_id', $linhas, null, ['class' => 'form-control', 'placeholder' => 'Selecione']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('descricao', 'Descrição') !!}
    {!! Form::textarea('descricao', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.linha-girante.produtos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/produtos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            <small>Linha Girante /</small> Produtos
            <a href="{{ route('painel.linha-girante.produtos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Produto</a>
        </h2>
    </legend>

    <div class="row" style="margin-bottom:20px">
        <div class="form-group col-sm-4">
            {!! Form::select('filtro', $categorias, Input::get('filtro'), ['class' => 'form-control', 'id' => 'filtro-select', 'placeholder' => 'Todas as Categorias', 'data-route' => 'painel/linha-girante/produtos']) !!}
        </div>
        <div class="col-sm-4" style="padding-left:0">
        <a href="{{ route('painel.linha-girante.produtos.categorias.index') }}" class="btn btn-primary btn-md"><span class="glyphicon glyphicon-edit" style="margin-right:10px;"></span><small>Editar Categorias</small></a>
        </div>
        @if(!$filtro)
        <div class="col-sm-4">
            <p class="alert alert-info small" style="margin-bottom: 15px; height:45px; padding: 12px 15px;">
                <span class="glyphicon glyphicon-info-sign" style="margin-right:10px;"></span>
                Selecione uma categoria para ordenar os produtos.
            </p>
        </div>
        @endif
    </div>

    @if(!count($produtos))
    <div class="alert alert-warning" role="alert">Nenhum produto cadastrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="produtos">
        <thead>
            <tr>
                @if($filtro)<th>Ordenar</th>@endif
                @if(!$filtro)<th>Categoria</th>@endif
                <th>Título</th>
                <th>Imagens</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($produtos as $produto)
            <tr class="tr-row" id="{{ $produto->id }}">
                @if($filtro)
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                @endif
                @if(!$filtro)
                <td>
                    @if($produto->categoria){{ $produto->categoria->titulo }}@endif
                </td>
                @endif
                <td>{{ $produto->titulo }}</td>
                <td><a href="{{ route('painel.linha-girante.produtos.imagens.index', $produto->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.linha-girante.produtos.destroy', $produto->id), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.linha-girante.produtos.edit', $produto->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection