laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('marcenaria-personalizada/{marcenaria_categoria?}', ['as' => 'marcenaria-personalizada', 'uses' => 'MarcenariaController@index']);

Route::get('linha-girante/{linha_categoria?}', ['as' => 'linha-girante', 'uses' => 'LinhaController@index']);
Route::get('linha-girante/{linha_categoria}/{linha_produto}/{linha_imagem?}', ['as' => 'linha-girante.produto', 'uses' => 'LinhaController@show']);

Route::get('quem-somos', ['as' => 'quem-somos', 'uses' => 'QuemSomosController@index']);

Route::get('novidades/data/{ano}/{mes?}', ['as' => 'novidades.data', 'uses' => 'BlogController@data']);
Route::get('novidades/{blog_categoria?}', ['as' => 'novidades', 'uses' => 'BlogController@index']);
Route::get('novidades/{blog_categoria}/{blog_post}', ['as' => 'novidades.post', 'uses' => 'BlogController@show']);
Route::post('novidades/{blog_categoria}/{blog_post}', ['as' => 'novidades.comentario', 'uses' => 'BlogController@comentario']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);

    Route::resource('banners', 'BannersController');

    Route::group(['prefix' => 'marcenaria-personalizada'], function() {
        Route::resource('projetos', 'ProjetosController');
        Route::resource('projetos.imagens', 'ProjetosImagensController');
        Route::resource('imagens/categorias', 'MarcenariaController');
        Route::resource('imagens', 'MarcenariaImagensController');
    });

    Route::group(['prefix' => 'linha-girante'], function() {
        Route::resource('linhas', 'LinhasController');
        Route::resource('linhas.imagens', 'LinhasImagensController');
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::resource('produtos.imagens', 'ProdutosImagensController');
    });

    Route::resource('quem-somos/parceiros', 'ParceirosController');
    Route::resource('quem-somos', 'QuemSomosController');

    Route::resource('novidades/categorias', 'BlogCategoriasController');
    Route::resource('novidades/comentarios', 'BlogComentariosController');
    Route::resource('novidades', 'BlogPostsController');
    Route::get('novidades/comentarios/{comentarios}/aprovacao/{value}', 'BlogComentariosController@aprovacao');
    Route::post('ckeditor-upload', 'BlogPostsController@imageUpload');

    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');

    Route::resource('usuarios', 'UsuariosController');
    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannerRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Helpers\CropImage;

class BannersController extends Controller
{
    private $image_config = [
        'width'  => 1980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannerRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar banner: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannerRequest $request, Banner $banner)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $banner->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar banner: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $banner)
    {
        try {

            $banner->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Banner excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir banner: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BlogCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BlogCategoriasRequest;
use App\Models\BlogCategoria;
use Illuminate\Http\Request;

class BlogCategoriasController extends Controller
{
    public function index()
    {
        $categorias = BlogCategoria::ordenados()->get();

        return view('painel.blog.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.blog.categorias.create');
    }

    public function store(BlogCategoriasRequest $request)
    {
        try {

            $input = $request->all();

            BlogCategoria::create($input);
            return redirect()->route('painel.novidades.categorias.index')->with('success', 'Categoria adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar categoria: '.$e->getMessage()]);

        }
    }

    public function edit(BlogCategoria $categoria)
    {
        return view('painel.blog.categorias.edit', compact('categoria'));
    }

    public function update(BlogCategoriasRequest $request, BlogCategoria $categoria)
    {
        try {

            $input = $request->all();

            $categoria->update($input);
            return redirect()->route('painel.novidades.categorias.index')->with('success', 'Categoria alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar categoria: '.$e->getMessage()]);

        }
    }

    public function destroy(BlogCategoria $categoria)
    {
        try {

            $categoria->delete();
            return redirect()->route('painel.novidades.categorias.index')->with('success', 'Categoria excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir categoria: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BlogComentariosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\BlogComentario;
use Illuminate\Http\Request;

class BlogComentariosController extends Controller
{
    public function index()
    {
        $comentarios = BlogComentario::with('post')->ordenados()->paginate(20);

        return view('painel.blog.comentarios', compact('comentarios'));
    }

    public function destroy(BlogComentario $comentario)
    {
        try {

            $comentario->delete();
            return redirect()->route('painel.novidades.comentarios.index')->with('success', 'Comentário excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir comentário: '.$e->getMessage()]);

        }
    }

    public function aprovacao(BlogComentario $comentario, $value)
    {
        $comentario->aprovado = $value;
        $comentario->save();
    }
}

laravel/app/Http/Controllers/Painel/BlogPostsController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Helpers\CropImage;
use App\Http\Controllers\Controller;
use App\Http\Requests\BlogPostsRequest;
use App\Models\BlogCategoria;
use App\Models\BlogPost;
use Illuminate\Http\Request;

class BlogPostsController extends Controller
{
    private $image_config = [
        'width'  => 380,
        'height' => null,
        'path'   => 'assets/img/blog/'
    ];

    private $categorias;

    public function __construct()
    {
        $this->categorias = BlogCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (BlogCategoria::find($filtro)) {
            $posts = BlogPost::ordenados()->categoria($filtro)->paginate(20);
        } else {
            $posts = BlogPost::ordenados()->paginate(20);
        }

        return view('painel.blog.index', compact('categorias', 'posts', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.blog.create', compact('categorias'));
    }

    public function store(BlogPostsRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            BlogPost::create($input);
            return redirect()->route('painel.novidades.index')->with('success', 'Post adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar post: '.$e->getMessage()]);

        }
    }

    public function edit(BlogPost $post)
    {
        $categorias = $this->categorias;

        return view('painel.blog.edit', compact('categorias', 'post'));
    }

    public function update(BlogPostsRequest $request, BlogPost $post)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $post->update($input);
            return redirect()->route('painel.novidades.index')->with('success', 'Post alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar post: '.$e->getMessage()]);

        }
    }

    public function destroy(BlogPost $post)
    {
        try {

            $post->delete();
            return redirect()->route('painel.novidades.index')->with('success', 'Post excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir post: '.$e->getMessage()]);

        }
    }

    public function imageUpload(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', [
                'width'  => 800,
                'height' => null,
                'path'   => 'assets/img/blog/imagens/'
            ]);
            $response = [
                'filepath' => asset('assets/img/blog/imagens/' . $imagem)
            ];
        }

        return response()->json($response);
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\ContatoRequest;

use App\Http\Controllers\Controller;
use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class HomeController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/LinhasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\LinhasRequest;
use App\Http\Controllers\Controller;

use App\Models\Linha;
use App\Helpers\CropImage;

class LinhasController extends Controller
{
    public function index()
    {
        $linhas = Linha::ordenados()->get();

        return view('painel.linhas.index', compact('linhas'));
    }

    public function create()
    {
        return view('painel.linhas.create');
    }

    public function store(LinhasRequest $request)
    {
        try {

            $input = $request->all();

            Linha::create($input);
            return redirect()->route('painel.linha-girante.linhas.index')->with('success', 'Linha adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar linha: '.$e->getMessage()]);

        }
    }

    public function edit(Linha $linha)
    {
        return view('painel.linhas.edit', compact('linha'));
    }

    public function update(LinhasRequest $request, Linha $linha)
    {
        try {

            $input = $request->all();

            $linha->update($input);
            return redirect()->route('painel.linha-girante.linhas.index')->with('success', 'Linha alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar linha: '.$e->getMessage()]);

        }
    }

    public function destroy(Linha $linha)
    {
        try {

            $linha->delete();
            return redirect()->route('painel.linha-girante.linhas.index')->with('success', 'Linha excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir linha: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/QuemSomosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\QuemSomosRequest;
use App\Http\Controllers\Controller;

use App\Models\QuemSomos;
use App\Helpers\CropImage;

class QuemSomosController extends Controller
{
    private $image_config = [
        'width'  => 400,
        'height' => null,
        'path'   => 'assets/img/quem-somos/'
    ];

    public function index()
    {
        $quemsomos = QuemSomos::first();

        return view('painel.quem-somos.index', compact('quemsomos'));
    }

    public function update(QuemSomosRequest $request, QuemSomos $quemsomos)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $quemsomos->update($input);
            return redirect()->route('painel.quem-somos.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>

    <li class="dropdown @if(str_is('painel.marcenaria-personalizada*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Marcenaria Personalizada
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.marcenaria-personalizada.projetos.index') }}">Projetos</a></li>
            <li><a href="{{ route('painel.marcenaria-personalizada.imagens.index') }}">Imagens</a></li>
        </ul>
    </li>

    <li class="dropdown @if(str_is('painel.linha-girante*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Linha Girante
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.linha-girante.linhas.index') }}">Linhas</a></li>
            <li><a href="{{ route('painel.linha-girante.produtos.index') }}">Produtos</a></li>
        </ul>
    </li>

    <li @if(str_is('painel.quem-somos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.quem-somos.index') }}">Quem Somos</a>
    </li>

    <li @if(str_is('painel.novidades*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.novidades.index') }}">Novidades</a>
    </li>

    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url() }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/painel/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/css/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/css/jquery.growl.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/css/bootstrap-multiselect.css') }}">
    <style type="text/css">#growls.default { top: 70px; }.growl { opacity: 1; }</style>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url() }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            Sistema <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/painel/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/jquery.growl.js') }}"></script>
    <script src="{{ asset('assets/painel/js/bootbox.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/bootstrap-multiselect.js') }}"></script>
    <script src="{{ asset('assets/painel/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/painel/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/js/painel.js') }}"></script>
</body>
</html>